/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import client.Encode;
import client.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author itcde
 */
public class FrmChangePassword extends javax.swing.JPanel {

    /**
     * Creates new form FrmChangePassword
     */
    public FrmChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPaFOldPass = new javax.swing.JPasswordField();
        jPaFNewPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPaFConfirmPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Change passoword");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Old password");

        jPaFOldPass.setForeground(new java.awt.Color(51, 51, 51));

        jPaFNewPass.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("New password");

        jPaFConfirmPass.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Confirm password");

        jButton1.setBackground(new java.awt.Color(7, 125, 180));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaFNewPass)
                            .addComponent(jPaFConfirmPass)
                            .addComponent(jPaFOldPass, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPaFOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPaFNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPaFConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(this.jPaFOldPass.getText().equals("")){
            this.jPaFOldPass.requestFocus();
            showDialog("You not enter old password");
        }
        else if(this.jPaFNewPass.getText().equals("")){
            this.jPaFNewPass.requestFocus();
            showDialog("You not enter new password");
        }
        else if(this.jPaFConfirmPass.getText().equals("")){
            this.jPaFConfirmPass.requestFocus();
            showDialog("You not enter confirm password");
        }
        else if(!this.jPaFNewPass.getText().equals(this.jPaFConfirmPass.getText())){
            this.jPaFNewPass.requestFocus();
            showDialog("New pass word and confirm password is not same");
        }
        else if(!Client.USER.getPassword().equals(Encode.encryptMD5(this.jPaFOldPass.getText()))){
            this.jPaFOldPass.requestFocus();
            showDialog("Old password invalid");
        }
        else{
            String pass = Encode.encryptMD5(this.jPaFNewPass.getText());
            Client.USER.setPassword(pass);
            Client.CLIENT.updateUser();
            JOptionPane.showMessageDialog(null, "Change password success");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void showDialog(String message){
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPaFConfirmPass;
    private javax.swing.JPasswordField jPaFNewPass;
    private javax.swing.JPasswordField jPaFOldPass;
    // End of variables declaration//GEN-END:variables
}
