/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import static client.GUI.Main.Y;
import client.GUI.small.Online;
import java.awt.Color;
import javax.swing.JList;

/**
 *
 * @author itcde
 */
public class FrmFriendList extends javax.swing.JPanel {
    private JList friendList;
    
    public int x = 0;
    public int y = 0;
    /**
     * Creates new form FrmFriendList
     */
    public FrmFriendList() {
        initComponents();
        
        friendList = new JList();
        
        jPnlOnline.add(friendList);
        friendList.setBounds(0, 0, 221, 418);
        Color color = new Color(229,249,249);
        friendList.setBackground(color);
    }
    
    //Load danh sách user đang online lên Frame Main thể hiện thông qua tên
    //Load userName của mỗi user lên jLblUserName
    //userNameList: danh sách user đang online
    //currentUserName: user hiện tại của client
   
    //Mỗi một user trong danh sách sẽ chứa tên đăng nhập và tên được ngăn cách với
    //Cắt chuỗi này ra ta sẽ được tên và tên đăng nhập của user đang online
    public void loadAllUserONline(String listUser, String currentUserName) {
        //Lấy userName đưa lên label
        String[] allUser = listUser.split(";");
        for (String item : allUser) {
            String[] temp = item.split("@");
            String userName = temp[0];
            String name = temp[1];
            System.out.println(userName + " " + name);
            if (!userName.equals(currentUserName)) {
                loadOnline(userName, name);
            }
        }
    }
    
    //Tải tất cả những người đang online lên list
    public void loadOnline(String userName, String name){
        Online online = new Online(userName, name, true);
        //Main.JCRP_ONLINE.add(online);
        Main.USER_ONLINE_LIST.add(online);
        online.setBounds(x, y, 221, 35);
        y += 35;
        
        //Yêu cầu lấy tên từ user
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPnlOnline = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("You can see who are your friends");

        javax.swing.GroupLayout jPnlOnlineLayout = new javax.swing.GroupLayout(jPnlOnline);
        jPnlOnline.setLayout(jPnlOnlineLayout);
        jPnlOnlineLayout.setHorizontalGroup(
            jPnlOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        jPnlOnlineLayout.setVerticalGroup(
            jPnlOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jPnlOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jPnlOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPnlOnline;
    // End of variables declaration//GEN-END:variables
}
