/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI;

import client.GUI.small.Loading;
import client.Client;
import client.GUI.register.FrmRegister;
import client.GUI.small.ForgotPassword;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author itcde
 */
public class FrmLogin extends javax.swing.JFrame {
    
    //Khi đăng thực hiện việc đăng nhập thì hiện panel này lên
    public static Loading LOADING;
    
    public static ForgotPassword FORGOT_PASSWORD;
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        
        this.jBtnLogin.setBorder(null);
        
        LOADING = new Loading();
        LOADING.setBounds(0, 0, 358, 460);
        this.add(LOADING);
        LOADING.setVisible(false);
        
        FORGOT_PASSWORD = new ForgotPassword();
        FORGOT_PASSWORD.setBounds(0, 0, 358, 460);
        this.add(FORGOT_PASSWORD);
        FORGOT_PASSWORD.setVisible(false);
        
        //Xét icon cho Frame
        ImageIcon icon = new ImageIcon("images/icons/logo.png");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNL_LOGIN = new javax.swing.JPanel();
        jTxtUserName = new javax.swing.JTextField();
        jBtnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnIRegister = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Talk talk");
        setResizable(false);

        JPNL_LOGIN.setBackground(new java.awt.Color(255, 255, 255));

        jTxtUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtUserName.setForeground(java.awt.Color.lightGray);
        jTxtUserName.setText("User name");
        jTxtUserName.setToolTipText("Username");
        jTxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyReleased(evt);
            }
        });

        jBtnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(0, 102, 255));
        jBtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/signin.png"))); // NOI18N
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Forget password");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/logo_2.png"))); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setToolTipText("Password");
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout JPNL_LOGINLayout = new javax.swing.GroupLayout(JPNL_LOGIN);
        JPNL_LOGIN.setLayout(JPNL_LOGINLayout);
        JPNL_LOGINLayout.setHorizontalGroup(
            JPNL_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_LOGINLayout.createSequentialGroup()
                .addGroup(JPNL_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNL_LOGINLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(JPNL_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(JPNL_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPNL_LOGINLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNL_LOGINLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(137, 137, 137))
        );

        JPNL_LOGINLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField1, jTxtUserName});

        JPNL_LOGINLayout.setVerticalGroup(
            JPNL_LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNL_LOGINLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(32, 32, 32))
        );

        JPNL_LOGINLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField1, jTxtUserName});

        jMenu1.setText("Account");

        jMnIRegister.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMnIRegister.setText("Resister");
        jMnIRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnIRegisterActionPerformed(evt);
            }
        });
        jMenu1.add(jMnIRegister);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Forgot password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        handelLogin();
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            handelLogin();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyPressed
        if(jTxtUserName.getText().equals("User name")){
            jTxtUserName.setText("");
            Color color = new Color(51, 51, 51);
            jTxtUserName.setForeground(color);
        }
    }//GEN-LAST:event_jTxtUserNameKeyPressed

    private void jTxtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyReleased
        if(jTxtUserName.getText().equals("")){
            jTxtUserName.setForeground(Color.LIGHT_GRAY);
            jTxtUserName.setText("User name");
        }
    }//GEN-LAST:event_jTxtUserNameKeyReleased

    private void jMnIRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnIRegisterActionPerformed
        FrmRegister frmRegister = new FrmRegister();
        frmRegister.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMnIRegisterActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmLogin.JPNL_LOGIN.setVisible(false);
        FrmLogin.LOADING.setVisible(false);
        FrmLogin.FORGOT_PASSWORD.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON1){
            FrmLogin.JPNL_LOGIN.setVisible(false);
            FrmLogin.LOADING.setVisible(false);
            FrmLogin.FORGOT_PASSWORD.setVisible(true);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void handelLogin() {
        
        FrmLogin.JPNL_LOGIN.setVisible(false);
        FrmLogin.FORGOT_PASSWORD.setVisible(false);
        FrmLogin.LOADING.setVisible(true);
        
        String userName = this.jTxtUserName.getText();
        String password = this.jPasswordField1.getText();

        if (userName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter username", "Login failed", JOptionPane.ERROR_MESSAGE);
            FrmLogin.LOADING.setVisible(false);
            FrmLogin.JPNL_LOGIN.setVisible(true);
            this.jTxtUserName.requestFocus();
            return;
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter password", "Login failed", JOptionPane.ERROR_MESSAGE);
            FrmLogin.LOADING.setVisible(false);
            this.jPasswordField1.requestFocus();
            FrmLogin.JPNL_LOGIN.setVisible(true);
            return;
        }
        
        Client.CLIENT = new Client(userName, password, this);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel JPNL_LOGIN;
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnIRegister;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables
}
