/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI.register;

import client.Check;
import java.awt.Color;
import javax.swing.JOptionPane;
import client.Client;
import static client.Encode.encryptMD5;

/**
 *
 * @author itcde
 */
public class AccountInformation extends javax.swing.JPanel{

    /**
     * Creates new form AccountInformation
     */
    public AccountInformation() {
        initComponents();
        
        //Chuyển vị trí chuột về đầu textfield
        this.jTxtUserName.setCaretPosition(0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtUserName = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jPwFConfirm = new javax.swing.JPasswordField();
        jPwFPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTxtUserName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTxtUserName.setForeground(java.awt.Color.lightGray);
        jTxtUserName.setText("User name");
        jTxtUserName.setToolTipText("User name");
        jTxtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUserNameKeyReleased(evt);
            }
        });

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTxtEmail.setForeground(java.awt.Color.lightGray);
        jTxtEmail.setText("Email");
        jTxtEmail.setToolTipText("Email");
        jTxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtEmailKeyReleased(evt);
            }
        });

        jPwFConfirm.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPwFConfirm.setForeground(java.awt.Color.lightGray);
        jPwFConfirm.setText("Confirm password");
        jPwFConfirm.setToolTipText("Confirm password");
        jPwFConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPwFConfirmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPwFConfirmKeyReleased(evt);
            }
        });

        jPwFPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPwFPass.setForeground(java.awt.Color.lightGray);
        jPwFPass.setText("Password");
        jPwFPass.setToolTipText("Password");
        jPwFPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPwFPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPwFPassKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Create new a account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPwFPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPwFConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPwFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPwFConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPwFConfirm, jPwFPass, jTxtEmail, jTxtUserName});

    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyPressed
        if(this.jTxtUserName.getText().equals("User name")){
            this.jTxtUserName.setText("");
            this.jTxtUserName.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_jTxtUserNameKeyPressed

    private void jTxtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUserNameKeyReleased
        if(this.jTxtUserName.getText().equals("")){
            this.jTxtUserName.setForeground(Color.LIGHT_GRAY);
            this.jTxtUserName.setText("User name");
            this.jTxtUserName.setCaretPosition(0);
        }
    }//GEN-LAST:event_jTxtUserNameKeyReleased

    private void jPwFPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwFPassKeyPressed
        if(this.jPwFPass.getText().equals("Password")){
            this.jPwFPass.setText("");
            this.jPwFPass.setForeground(new Color(51, 51, 51));
            
        }
    }//GEN-LAST:event_jPwFPassKeyPressed

    private void jPwFPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwFPassKeyReleased
        if(this.jPwFPass.getText().equals("")){
            this.jPwFPass.setForeground(Color.LIGHT_GRAY);
            this.jPwFPass.setText("Password");
            this.jPwFPass.setCaretPosition(0);
        }
    }//GEN-LAST:event_jPwFPassKeyReleased

    private void jPwFConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwFConfirmKeyPressed
        if(this.jPwFConfirm.getText().equals("Confirm password")){
            this.jPwFConfirm.setText("");
            this.jPwFConfirm.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_jPwFConfirmKeyPressed

    private void jPwFConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPwFConfirmKeyReleased
        if(this.jPwFConfirm.getText().equals("")){
            this.jPwFConfirm.setForeground(Color.LIGHT_GRAY);
            this.jPwFConfirm.setText("Confirm password");
            this.jPwFConfirm.setCaretPosition(0);
        }
    }//GEN-LAST:event_jPwFConfirmKeyReleased

    private void jTxtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEmailKeyPressed
        if(this.jTxtEmail.getText().equals("Email")){
            this.jTxtEmail.setText("");
            this.jTxtEmail.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_jTxtEmailKeyPressed

    private void jTxtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEmailKeyReleased
        if(this.jTxtEmail.getText().equals("")){
            this.jTxtEmail.setForeground(Color.LIGHT_GRAY);
            this.jTxtEmail.setText("Email");
            this.jTxtEmail.setCaretPosition(0);
        }
    }//GEN-LAST:event_jTxtEmailKeyReleased

    public boolean checkInfo(){
        if(this.jTxtUserName.getText().equals("") || this.jTxtUserName.getText().equals("User name")){
            errorReport("Please enter the name!!!");
            this.jTxtUserName.requestFocus();
            return false;
        }
        if(!Check.checkName(this.jTxtUserName.getText())){
            errorReport("User name incorrect format. User name only include non-accented characters!!!");
            this.jTxtUserName.requestFocus();
            return false;
        }
        //Kiểm tra username đã tồn tại hay chưa bằng cách gửi userName lên server để kiểm tra
        if(Client.CLIENT.checkExistUser(this.jTxtUserName.getText()) == true){
            errorReport("User name already exist!!");
            this.jTxtUserName.requestFocus();
            return false;
        }
        if(this.jPwFConfirm.getText().equals("") || this.jPwFConfirm.getText().equals("Password")){
            errorReport("Please enter password!!!");
            this.jPwFPass.requestFocus();
            return false;
        }
        if(this.jPwFConfirm.getText().equals("") || this.jPwFConfirm.getText().equals("Confirm password")){
            errorReport("Please confirm password!!!");
            this.jPwFPass.requestFocus();
            return false;
        }
        if(!this.jPwFPass.getText().equals(this.jPwFConfirm.getText())){
            errorReport("Confirm password is incorrect!!!");
            this.jPwFPass.requestFocus();
            return false;
        }
        if(this.jTxtEmail.getText().equals("") || this.jTxtEmail.getText().equals("Email")){
            errorReport("Please enter is email!!!");
            this.jTxtEmail.requestFocus();  
            return false;
        }
        if(!Check.checkEmail(this.jTxtEmail.getText())){
            errorReport("Email incorrect format!!!");
            this.jTxtEmail.requestFocus();
            return false;
        }
        
        return true;
    }
    
    public void setAccountInformation(){
       FrmRegister.USER_NAME = this.jTxtUserName.getText();
       FrmRegister.PASSWORD = encryptMD5(this.jPwFPass.getText());
       FrmRegister.EMAIL = this.jTxtEmail.getText();
    }
    
    public void errorReport(String message){
        JOptionPane.showMessageDialog(null, message, "Register failed", JOptionPane.ERROR_MESSAGE);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwFConfirm;
    private javax.swing.JPasswordField jPwFPass;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables

}
