/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI.register;

import client.Client;
import client.EmailSender;
import client.GUI.FrmProfile;
import static client.GUI.FrmProfile.CHANGE_FOREGROUD_LABEL;
import static client.GUI.FrmProfile.JTXT_GENDER;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author itcde
 */
public class ConfirmationEmail extends javax.swing.JPanel {
    private String _confirmCode;
    private String _email = "";
    
    /**
     * Creates new form CofirmationEmail
     * @param email
     */
    public ConfirmationEmail(String email) {
        initComponents();
        
        this._email = email;
        jBtnConfirm.setVisible(false);
    }
    
    public ConfirmationEmail(boolean visiable, String email){
        initComponents();
        
        this._email = email;
        sendConfirmCode();
    }
    
    //Tạo ra 1 số ngẫu nhiên từ 1001 - 9999
    public String randomCode(){
        Random rand = new Random();
        while(true){
            int temp = rand.nextInt() % 10000;
            if(temp > 1000){
                return temp + "";
            }
        }
    }
    
    public void sendConfirmCode(){
        _confirmCode = randomCode();
        String message = "Your email confirm code TalkTalk is: <h3>" + _confirmCode + "</h3>"
                + "never share this code for anyone";
        EmailSender.sendMail(this._email, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtConfirmCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnConfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Confirmation email");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("A confirmation code has been sent to your email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Please enter it to continue:");

        jTxtConfirmCode.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/refresh.png"))); // NOI18N
        jButton1.setToolTipText("Resend the code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("This can take a long time.");

        jBtnConfirm.setBackground(new java.awt.Color(7, 125, 180));
        jBtnConfirm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfirm.setText("Confirm");
        jBtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jTxtConfirmCode, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jBtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtConfirmCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendConfirmCode();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmActionPerformed
        if(checkInfor() == false){
            JOptionPane.showMessageDialog(null, "Confirm code is invalid", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTxtConfirmCode.setText("");
        }
        else{
            Client.USER.setEmail(FrmProfile.JTXT_EMAIL.getText());
            Client.CLIENT.updateUser();

            FrmProfile.JLBL_SAVE_EMAIL.setText("         ");
            CHANGE_FOREGROUD_LABEL(FrmProfile.JLBL_CANCEL_EMAIL, "GRAY");
            FrmProfile.JLBL_CANCEL_EMAIL.setText("   Public");
            JTXT_GENDER.setEditable(false);
            FrmProfile.JTXT_EMAIL.setBorder(null);
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_jBtnConfirmActionPerformed
    
    public boolean checkInfor(){
        if(this.jTxtConfirmCode.getText().equals(_confirmCode)){
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null, "Confirm code is invalid", "Error", JOptionPane.ERROR_MESSAGE);
            this.jTxtConfirmCode.setText("");
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtConfirmCode;
    // End of variables declaration//GEN-END:variables
}
