/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI.register;

import client.DAO.UserDAO;
import client.Client;
import client.DTO.User;
import client.GUI.FrmLogin;
import client.GUI.small.Loading;
import javax.swing.ImageIcon;

/**
 *
 * @author itcde
 */
public class FrmRegister extends javax.swing.JFrame {
    public static String FIRST_NAME;
    public static String LAST_NAME;
    public static String BIRTH_DATE;
    public static String GENDER;
    public static String USER_NAME;
    public static String PASSWORD;
    public static String PATH_AVARTAR;
    public static String EMAIL;
    
    //Việc đăng kí sẽ tiến hành qua 4 bước
    //Thuộc tính này sẽ cho biết bước nào đang thực hiện
    //Bắt đầu sẽ là 1
    private int _panelNumber = 1;
    
    //4 bước sẽ bao gồm 
    AccountInformation acountInfo;
    ConfirmationEmail confirEmail;
    PersonalInformation personalInfo;
    RegisterSuccess registerSuccess;
    
    private Loading load;
    
    /**
     * Creates new form FrmRegister
     */
    public FrmRegister() {
        
        initComponents();
        
        
        
        load = new Loading();
        load.setBounds(0, 0, 604, 466);
        this.add(load);
        load.setVisible(false);

        this.acountInfo = new AccountInformation();
        this.personalInfo = new PersonalInformation();
        this.registerSuccess = new RegisterSuccess();
        
        //Tải frame accountInformation lên jPnlContent
        handleRegister();
        
        //Khai báo một client để kiểm tra tài khoản có tồn tại hay chưa khi đăng kí
        Client.CLIENT = new Client();
        
        //Xét icon cho Frame
        ImageIcon icon = new ImageIcon("images/icons/logo.png");
        this.setIconImage(icon.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPnlMain = new javax.swing.JPanel();
        jPnlContent = new javax.swing.JPanel();
        jBtnBack = new javax.swing.JButton();
        jBtnNext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register - Talk Talk");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPnlMain.setBackground(new java.awt.Color(255, 255, 255));

        jPnlContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPnlContentLayout = new javax.swing.GroupLayout(jPnlContent);
        jPnlContent.setLayout(jPnlContentLayout);
        jPnlContentLayout.setHorizontalGroup(
            jPnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPnlContentLayout.setVerticalGroup(
            jPnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jBtnBack.setBackground(new java.awt.Color(255, 255, 255));
        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/back.png"))); // NOI18N
        jBtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jBtnNext.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/icons/next.png"))); // NOI18N
        jBtnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMainLayout = new javax.swing.GroupLayout(jPnlMain);
        jPnlMain.setLayout(jPnlMainLayout);
        jPnlMainLayout.setHorizontalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMainLayout.createSequentialGroup()
                .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlMainLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlMainLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPnlMainLayout.setVerticalGroup(
            jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jMenu1.setText("Talk");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed

        if(this._panelNumber == 1){
            return;
        }
        _panelNumber--;
        handleRegister();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNextActionPerformed
        
        //Hiển thị form loading
        //Ẩn form đăng kí tài khoản
        jPnlMain.setVisible(false);
        load.setVisible(true);
        
        boolean check = true;
        switch (_panelNumber) {
            case 1:
                if(!acountInfo.checkInfo()){
                    check = false;
                    break;
                }   
                acountInfo.setAccountInformation();
                
                //Gửi mã xác nhận tới email đăng kí trước khi load Frame xác nhận email
                this.confirEmail = new ConfirmationEmail(FrmRegister.EMAIL);
                confirEmail.sendConfirmCode();
                
                break;
            case 2:
                if(!confirEmail.checkInfor()){
                    check = false;
                    break;
                }
                break;
            case 3:
                if(!personalInfo.checkInfo()){
                    check = false;
                    break;
                }   
                personalInfo.setAccountInformation();
                
                //Thực hiện việc đăng kí tài khoản
                //Xét avartar mặc định cho user. Nam và nữ có avartar mặc định khác nhau
                if(GENDER.equals("Male")){
                    PATH_AVARTAR = "images/avartar/boy.jpg";
                }
                else{
                    PATH_AVARTAR = "images/avartar/girl.png";
                }
                
                User user = new User(FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, USER_NAME, PASSWORD, EMAIL, PATH_AVARTAR);
                String sql = new UserDAO().getStringInsertUser(user);
                Client.CLIENT.insertUser(sql);
                
                break;            
        }
        
        //Hiển thị form đăng kí tài khoản
        //ẩn form loading
        jPnlMain.setVisible(true);
        load.setVisible(false);
        if(check == true){
            _panelNumber++;
            handleRegister();
        }
    }//GEN-LAST:event_jBtnNextActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void handleRegister(){
        load.setVisible(false);
        this.jPnlMain.setVisible(true);
        switch (_panelNumber) {
            case 1:
                this.jPnlContent.removeAll();
                jPnlContent.revalidate();
                this.jPnlContent.repaint();
                this.jPnlContent.add(acountInfo);
                acountInfo.setBounds(0, 0, 369, 345);
                acountInfo.setVisible(true);
                break;
            case 2:
                this.jPnlContent.removeAll();
                jPnlContent.revalidate();
                this.jPnlContent.repaint();
                this.jPnlContent.add(confirEmail);
                confirEmail.setBounds(0, 0, 369, 345);
                confirEmail.setVisible(true);
                break;
            case 3:
                this.jPnlContent.removeAll();
                jPnlContent.revalidate();
                this.jPnlContent.repaint();
                this.jPnlContent.add(personalInfo);
                personalInfo.setBounds(0, 0, 369, 345);
                personalInfo.setVisible(true);
                break;
            case 4:
                this.jPnlContent.removeAll();
                jPnlContent.revalidate();
                this.jPnlContent.repaint();
                this.jPnlContent.add(registerSuccess);
                registerSuccess.setBounds(0, 0, 369, 345);
                registerSuccess.setVisible(true);
                
                //Ẩn hai button
                this.jBtnBack.setVisible(false);
                this.jBtnNext.setVisible(false);
                this.jPnlMain.setSize(605, 605);
                
                
                break;
            default:
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPnlContent;
    private javax.swing.JPanel jPnlMain;
    // End of variables declaration//GEN-END:variables
}
