/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.GUI.register;

import client.Check;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author itcde
 */
public class PersonalInformation extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public PersonalInformation() {
        initComponents();
    }
    
    public PersonalInformation(String s) {
        
    }
    
    public Date convertFromStringToDate(String dateStr){
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;
        try {
            date = df.parse(dateStr);
        } catch (ParseException ex) {
            Logger.getLogger(PersonalInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        return date;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtFirstName = new javax.swing.JTextField();
        jTxtLastName = new javax.swing.JTextField();
        jCbxDate = new javax.swing.JComboBox<>();
        jCbxMonth = new javax.swing.JComboBox<>();
        jCbxYear = new javax.swing.JComboBox<>();
        jCbxGender = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("More your information");

        jTxtFirstName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTxtFirstName.setForeground(java.awt.Color.lightGray);
        jTxtFirstName.setText("First name");
        jTxtFirstName.setToolTipText("First name");
        jTxtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFirstNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtFirstNameKeyReleased(evt);
            }
        });

        jTxtLastName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTxtLastName.setForeground(java.awt.Color.lightGray);
        jTxtLastName.setText("Last name");
        jTxtLastName.setToolTipText("Last name");
        jTxtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtLastNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtLastNameKeyReleased(evt);
            }
        });

        jCbxDate.setForeground(new java.awt.Color(51, 51, 51));
        jCbxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day of birth", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCbxMonth.setForeground(new java.awt.Color(51, 51, 51));
        jCbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month of birth", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jCbxYear.setForeground(new java.awt.Color(51, 51, 51));
        jCbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year of birth", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));

        jCbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Famale", "Orther" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtFirstName)
                    .addComponent(jTxtLastName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCbxDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbxMonth, 0, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCbxDate, jCbxMonth});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(37, 37, 37)
                .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jCbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCbxDate, jCbxGender, jCbxMonth, jCbxYear, jTxtLastName});

    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFirstNameKeyPressed
        if(this.jTxtFirstName.getText().equals("First name")){
            this.jTxtFirstName.setText("");
            this.jTxtFirstName.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_jTxtFirstNameKeyPressed

    private void jTxtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFirstNameKeyReleased
        if(this.jTxtFirstName.getText().equals("")){
            this.jTxtFirstName.setForeground(Color.LIGHT_GRAY);
            this.jTxtFirstName.setText("First name");
        }
    }//GEN-LAST:event_jTxtFirstNameKeyReleased

    private void jTxtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLastNameKeyPressed
        if(this.jTxtLastName.getText().equals("Last name")){
            this.jTxtLastName.setText("");
            this.jTxtLastName.setForeground(new Color(51, 51, 51));
        }
    }//GEN-LAST:event_jTxtLastNameKeyPressed

    private void jTxtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLastNameKeyReleased
        if(this.jTxtLastName.getText().equals("")){
            this.jTxtLastName.setForeground(Color.LIGHT_GRAY);
            this.jTxtLastName.setText("Last name");
        }
    }//GEN-LAST:event_jTxtLastNameKeyReleased
    
    public boolean checkInfo(){
        if(this.jTxtFirstName.getText().equals("")){
            errorReport("Please fill full the information");
            this.jTxtFirstName.requestFocus();
            return false;
        }
        else if(!Check.checkName(this.jTxtFirstName.getText())){
            errorReport("First name incorrect format. Only include non-accented characters!!!");
            this.jTxtFirstName.requestFocus();
            return false;
        }
        else if(this.jTxtLastName.getText().equals("")){
            errorReport("Please fill full the information");
            this.jTxtLastName.requestFocus();
            return false;
        }
        else if(!Check.checkName(this.jTxtLastName.getText())){
            errorReport("Last name incorrect format. Only include non-accented characters!!!");
            this.jTxtLastName.requestFocus();
            return false;
        }
        else if(this.jCbxDate.getSelectedItem().equals("Day of birth")){
            errorReport("Please choice day of birth");
            return false;
        }
        else if(this.jCbxMonth.getSelectedItem().equals("Month of birth")){
            errorReport("Please choice month of birth");
            return false;
        }
        else if(this.jCbxYear.getSelectedItem().equals("Year of birth")){
            errorReport("Please choice year of birth");
            return false;
        }
        else if(this.jCbxGender.getSelectedItem().equals("Day of birth")){
            errorReport("Please choice gender");
            return false;
        }
        return true;
    }
    
    public void setAccountInformation(){
        FrmRegister.FIRST_NAME = this.jTxtFirstName.getText();
        FrmRegister.LAST_NAME = this.jTxtLastName.getText();
        FrmRegister.BIRTH_DATE = this.jCbxYear.getSelectedItem().toString() + "/" + this.jCbxMonth.getSelectedItem().toString() 
                + "/" + this.jCbxDate.getSelectedItem().toString();
        FrmRegister.GENDER = this.jCbxGender.getSelectedItem().toString();
    }
    
    private void errorReport(String message){
        JOptionPane.showMessageDialog(null, message, "Register failed", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbxDate;
    private javax.swing.JComboBox<String> jCbxGender;
    private javax.swing.JComboBox<String> jCbxMonth;
    private javax.swing.JComboBox<String> jCbxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
